package com.jeong.runninggoaltracker.domain.contract

const val SQUAT_MIN_LANDMARK_CONFIDENCE = 0.6f
const val SQUAT_EMA_ALPHA = 0.3f
const val SQUAT_CALIBRATION_REQUIRED_FRAMES = 30
const val SQUAT_STATE_HYSTERESIS_FRAMES = 3
const val SQUAT_UP_FRAMES_REQUIRED = 3
const val SQUAT_DOWN_FRAMES_REQUIRED = 3
const val SQUAT_SIDE_SELECTION_STABLE_WINDOW_MS = 700L
const val SQUAT_STANDING_KNEE_ANGLE_THRESHOLD = 165f
const val SQUAT_DESCENDING_KNEE_ANGLE_THRESHOLD = 150f
const val SQUAT_BOTTOM_KNEE_ANGLE_THRESHOLD = 105f
const val SQUAT_ASCENDING_KNEE_ANGLE_THRESHOLD = 115f
const val SQUAT_REP_COMPLETE_KNEE_ANGLE_THRESHOLD = 165f
const val SQUAT_GOOD_DEPTH_ANGLE_THRESHOLD = 100f
const val SQUAT_SHALLOW_DEPTH_ANGLE_THRESHOLD = 120f
const val SQUAT_MAX_TRUNK_LEAN_ANGLE_THRESHOLD = 30f
const val SQUAT_HEEL_RISE_RATIO_THRESHOLD = 0.06f
const val SQUAT_KNEE_FORWARD_RATIO_THRESHOLD = 0.15f
const val SQUAT_FLOAT_ZERO = 0f
const val SQUAT_FLOAT_ONE = 1f
const val SQUAT_FLOAT_TWO = 2f
const val SQUAT_FLOAT_NEGATIVE_ONE = -1f
const val SQUAT_INT_ZERO = 0
const val SQUAT_INT_ONE = 1
const val SQUAT_REASON_DOWN_THRESHOLD = "down_threshold"
const val SQUAT_REASON_UP_THRESHOLD = "up_threshold"
